### ISSUE TITLE
Deploy Kubeflow on Kubernetes 

### ISSUE THREAD

**Issue by vigosser** [kubeflow/website#931]
https://www.kubeflow.org/docs/started/getting-started-k8s/

Here is the problem.

```
$kfctl apply all -V

INFO[0082] Trying to get istio-ingressgateway Service External IP  filename="existing_arrikto/existing.go:392"
INFO[0092] Trying to get istio-ingressgateway Service External IP  filename="existing_arrikto/existing.go:392"
INFO[0102] Trying to get istio-ingressgateway Service External IP  filename="existing_arrikto/existing.go:392"
INFO[0112] Trying to get istio-ingressgateway Service External IP  filename="existing_arrikto/existing.go:392"
INFO[0122] Trying to get istio-ingressgateway Service External IP  filename="existing_arrikto/existing.go:392"
INFO[0132] Trying to get istio-ingressgateway Service External IP  filename="existing_arrikto/existing.go:392"
INFO[0142] Trying to get istio-ingressgateway Service External IP  filename="existing_arrikto/existing.go:392"
INFO[0152] Trying to get istio-ingressgateway Service External IP  filename="existing_arrikto/existing.go:392"
INFO[0162] Trying to get istio-ingressgateway Service External IP  filename="existing_arrikto/existing.go:392"
INFO[0172] Trying to get istio-ingressgateway Service External IP  filename="existing_arrikto/existing.go:392"
INFO[0182] Trying to get istio-ingressgateway Service External IP  filename="existing_arrikto/existing.go:392"
INFO[0192] Trying to get istio-ingressgateway Service External IP  filename="existing_arrikto/existing.go:392"
INFO[0202] Trying to get istio-ingressgateway Service External IP  filename="existing_arrikto/existing.go:392"
INFO[0212] Trying to get istio-ingressgateway Service External IP  filename="existing_arrikto/existing.go:392"
INFO[0222] Trying to get istio-ingressgateway Service External IP  filename="existing_arrikto/existing.go:392"
INFO[0232] Trying to get istio-ingressgateway Service External IP  filename="existing_arrikto/existing.go:392"
INFO[0242] Trying to get istio-ingressgateway Service External IP  filename="existing_arrikto/existing.go:392"
INFO[0252] Trying to get istio-ingressgateway Service External IP  filename="existing_arrikto/existing.go:392"
INFO[0262] Trying to get istio-ingressgateway Service External IP  filename="existing_arrikto/existing.go:392"
INFO[0272] Trying to get istio-ingressgateway Service External IP  filename="existing_arrikto/existing.go:392"
INFO[0282] Trying to get istio-ingressgateway Service External IP  filename="existing_arrikto/existing.go:392"
couldn't apply KfApp:  (kubeflow.error): Code 500 with message: coordinator Apply failed for existing_arrikto:  (kubeflow.error): Code 500 with message: timed out while waiting to get istio-ingressgateway Service ExternalIP
github.com/kubeflow/kubeflow/bootstrap/v2/pkg/kfapp/existing_arrikto.getEndpoints
        /go/src/github.com/kubeflow/kubeflow/bootstrap/v2/pkg/kfapp/existing_arrikto/existing.go:288
github.com/kubeflow/kubeflow/bootstrap/v2/pkg/kfapp/existing_arrikto.(*Existing).Apply
        /go/src/github.com/kubeflow/kubeflow/bootstrap/v2/pkg/kfapp/existing_arrikto/existing.go:140
github.com/kubeflow/kubeflow/bootstrap/pkg/kfapp/coordinator.(*coordinator).Apply.func1
        /go/src/github.com/kubeflow/kubeflow/bootstrap/pkg/kfapp/coordinator/coordinator.go:701
github.com/kubeflow/kubeflow/bootstrap/pkg/kfapp/coordinator.(*coordinator).Apply
        /go/src/github.com/kubeflow/kubeflow/bootstrap/pkg/kfapp/coordinator/coordinator.go:737
github.com/kubeflow/kubeflow/bootstrap/cmd/kfctl/cmd.glob..func1
        /go/src/github.com/kubeflow/kubeflow/bootstrap/cmd/kfctl/cmd/apply.go:46
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
github.com/kubeflow/kubeflow/bootstrap/cmd/kfctl/cmd.Execute
        /go/src/github.com/kubeflow/kubeflow/bootstrap/cmd/kfctl/cmd/root.go:61
main.main
        /go/src/github.com/kubeflow/kubeflow/bootstrap/cmd/kfctl/main.go:36
runtime.main
        /usr/local/go/src/runtime/proc.go:200
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1337
github.com/kubeflow/kubeflow/bootstrap/v2/pkg/kfapp/existing_arrikto.(*Existing).Apply
        /go/src/github.com/kubeflow/kubeflow/bootstrap/v2/pkg/kfapp/existing_arrikto/existing.go:142
github.com/kubeflow/kubeflow/bootstrap/pkg/kfapp/coordinator.(*coordinator).Apply.func1
        /go/src/github.com/kubeflow/kubeflow/bootstrap/pkg/kfapp/coordinator/coordinator.go:701
github.com/kubeflow/kubeflow/bootstrap/pkg/kfapp/coordinator.(*coordinator).Apply
        /go/src/github.com/kubeflow/kubeflow/bootstrap/pkg/kfapp/coordinator/coordinator.go:737
github.com/kubeflow/kubeflow/bootstrap/cmd/kfctl/cmd.glob..func1
        /go/src/github.com/kubeflow/kubeflow/bootstrap/cmd/kfctl/cmd/apply.go:46
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
github.com/kubeflow/kubeflow/bootstrap/cmd/kfctl/cmd.Execute
        /go/src/github.com/kubeflow/kubeflow/bootstrap/cmd/kfctl/cmd/root.go:61
main.main
        /go/src/github.com/kubeflow/kubeflow/bootstrap/cmd/kfctl/main.go:36
runtime.main
        /usr/local/go/src/runtime/proc.go:200
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1337
```

The problem  occured when I follow the step of "Kubeflow on Kubernetes", and typing the `kfctl apply all -V` commond. Seems kfctl failed get istio-ingressgateway Service ExternalIP.  The status of istio as fllow.
```
root@ubuntu:/home/ubuntu/kfctl-0.6/my-app# kubectl get pods -n istio-system
NAME                                      READY   STATUS      RESTARTS   AGE
grafana-67c69bb567-jzxkd                  1/1     Running     0          27h
istio-citadel-67697b6697-zz7mj            1/1     Running     0          27h
istio-cleanup-secrets-1.1.6-sjbmg         0/1     Completed   0          27h
istio-egressgateway-7dbbb87698-n4st2      1/1     Running     0          27h
istio-galley-7474d97954-fqdb5             1/1     Running     0          27h
istio-grafana-post-install-1.1.6-8dm4c    0/1     Completed   0          27h
istio-ingressgateway-565b894b5f-wrhkg     1/1     Running     0          27h
istio-pilot-6dd5b8f74c-8xzxz              2/2     Running     0          17h
istio-pilot-6dd5b8f74c-xwqnr              0/2     Evicted     0          27h
istio-policy-7f8bb87857-67swq             2/2     Running     3          27h
istio-security-post-install-1.1.6-4d2f5   0/1     Completed   0          27h
istio-sidecar-injector-fd5875568-rbqvl    1/1     Running     0          27h
istio-telemetry-8759dc6b7-7lh47           2/2     Running     4          27h
istio-tracing-5d8f57c8ff-dgzm6            1/1     Running     0          27h
kiali-d4d886dd7-2v2x9                     1/1     Running     0          27h
prometheus-d8d46c5b5-6b8h6                1/1     Running     0          27h
```

**Comment by vigosser** [comment]
The problem solved by rasing the server's memory form 2G to 8G.

**Comment by yanniszark** [comment]
Hi @vigosser.
The installation requires access to a working LoadBalancerService, as mentioned by the Prerequisites.
You can use [MetalLB](https://metallb.universe.tf/) or try it out in a compliant GKE cluster, using the script provided in the guide.

**Comment by futeng** [comment]
Hi @yanniszark 
The problem still there after installed MetalLB.

After try `kfctl apply all -V`. Really need help.

```shell
...
INFO[0044] Trying to get istio-ingressgateway Service Address from its Status  filename="existing_arrikto/existing.go:414"
```

- docker: 19.03
- Kubernetes：v1.15.1

```shell
[root@k8s123 ~]# kubectl get nodes
NAME     STATUS   ROLES    AGE   VERSION
k8s122   Ready    master   46h   v1.15.1
k8s123   Ready    <none>   46h   v1.15.1
```

```shell
[root@k8s123 ~]#  kubectl get pods --all-namespaces
NAMESPACE        NAME                                      READY   STATUS      RESTARTS   AGE
istio-system     grafana-86f89dbd84-zjx9z                  1/1     Running     1          85m
istio-system     istio-citadel-74966f47d6-2k574            1/1     Running     1          85m
istio-system     istio-cleanup-secrets-1.1.6-ntxcs         0/1     Completed   0          27h
istio-system     istio-egressgateway-5c64d575bc-kv85q      1/1     Running     1          29h
istio-system     istio-galley-8bdbffd7-ttklz               1/1     Running     2          85m
istio-system     istio-grafana-post-install-1.1.6-scrgg    0/1     Completed   0          27h
istio-system     istio-ingressgateway-589ff776dd-2b9tt     1/1     Running     1          27h
istio-system     istio-pilot-677df6b6d4-7c8gq              2/2     Running     190        27h
istio-system     istio-policy-6f74d9d95d-vpzms             2/2     Running     566        27h
istio-system     istio-security-post-install-1.1.6-ndps2   0/1     Completed   0          27h
istio-system     istio-sidecar-injector-866f4b98c7-bn2fr   1/1     Running     2          85m
istio-system     istio-telemetry-549c8f9dcb-d44g2          2/2     Running     597        29h
istio-system     istio-tracing-555cf644d-85rmj             1/1     Running     2          29h
istio-system     kiali-7db44d6dfb-2wpxt                    1/1     Running     1          29h
istio-system     prometheus-d44645598-gtnsv                1/1     Running     2          85m
kube-system      coredns-5c98db65d4-72qqj                  1/1     Running     2          46h
kube-system      coredns-5c98db65d4-bqvzd                  1/1     Running     2          46h
kube-system      etcd-k8s122                               1/1     Running     1          46h
kube-system      kube-apiserver-k8s122                     1/1     Running     1          46h
kube-system      kube-controller-manager-k8s122            1/1     Running     1          46h
kube-system      kube-flannel-ds-amd64-4s4cj               1/1     Running     0          62m
kube-system      kube-flannel-ds-amd64-l29md               1/1     Running     1          46h
kube-system      kube-proxy-9rr8r                          1/1     Running     0          62m
kube-system      kube-proxy-wchmk                          1/1     Running     2          46h
kube-system      kube-scheduler-k8s122                     1/1     Running     1          46h
metallb-system   controller-55d74449-75445                 1/1     Running     1          28m
metallb-system   speaker-6456z                             1/1     Running     0          13m
metallb-system   speaker-qszk7                             1/1     Running     1          28m
```

**Comment by yanniszark** [comment]
@futeng please see this comment:
https://github.com/kubeflow/kubeflow/issues/3737#issuecomment-516700738

**Comment by yanniszark** [comment]
@futeng did you manage to successfully install MetalLB and subsequently, `kfctl_existing_arrikto` ?

**Comment by sarahmaddox** [comment]
I'm going to close this issue, as it's been a while since there was any activity on the issue and we've significantly updated the installation process since the issue was reported.

/close
